### ISSUE TITLE
Unable to load device tree: GPIO_..

### ISSUE THREAD

**Issue by timkalinowski** [notnyt/beaglebone#2]
Hi, this looks like a great library and i've had no issues with Analog Inputs although keep running into the same issue with digital pins, my understanding is the library sets up the pins and device tree when you create a GPIO object although I keep getting the following errors. Application is run as root, SLOTS shows the creation of the ADC cape, although GPIO fails, i'm getting my head around device trees so apologies if this is to do with configuration. 
Distro: Debian GNU/Linux 7 (wheezy)

 0: 54:PF---
 1: 55:PF---
 2: 56:PF---
 3: 57:PF---
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
 7: ff:P-O-L Override Board Name,00A0,Override Manuf,BB-ADC

E, [2014-06-03T15:34:48.083417 #2244] ERROR -- : Unable to load device tree: GPIO_P9_12_0x37 (StandardError)
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/beaglebone.rb:258:in 'device_tree_load'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/gpio.rb:114:in 'pin_mode'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/gpio.rb:606:in 'initialize'
/home/timmeh/aquamicro/lib/daemons/io_monitor.rb:36:in 'new'
/h
E, [2014-06-03T15:34:48.086614 #2244] ERROR -- : No such file or directory - /sys/devices/bone_capemgr.9/slots (Errno::ENOENT)
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/beaglebone.rb:256:in 'close'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/beaglebone.rb:256:in 'open'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/beaglebone.rb:256:in 'device_tree_load'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/gpio.rb:114:in 'pin_mode'
/var/lib/gems/1.9.1/gems/beaglebone-1.2.1/lib/beaglebone/gpio.rb:606:in 'initialize'
/home/timmeh/aquamicro/lib/daemons/io_monitor.rb:36:in 'new'
/home/timmeh/aquamicro/lib/daemons/io_monitor.rb:36:in '<top (required)>'

Cheers!

**Comment by Luis-Castillo** [comment]
Hi. I'm just starting with my beaglebone and wish to use this library with the debian console build. I installed ruby and the gem and get the "unable to load device tree" error.  If I use the default lxde build everything works fine, so it's obvious to me I'm missing some configuration from my part. 
Is there a reference I could use on how to setup debian to run this library? Sorry to ask this here but don't know where to look. Thanks.

**Comment by notnyt** [comment]
Are you running as root?  Please paste the code you're running and the output from running it.  What version image do you have installed?

**Comment by Luis-Castillo** [comment]
Hi, thanks for the quick response.

I try:

require 'beaglebone'
include Beaglebone

pin = GPIOPin.new :P9_12, :OUT

and get:

/var/lib/gems/1.9.1/gems/beaglebone-1.2.6/lib/beaglebone/beaglebone.rb:257:in `device_tree_load': Unable to load device tree: GPIO_P9_12_0x17 (StandardError)
	from /var/lib/gems/1.9.1/gems/beaglebone-1.2.6/lib/beaglebone/gpio.rb:114:in `pin_mode'
	from /var/lib/gems/1.9.1/gems/beaglebone-1.2.6/lib/beaglebone/gpio.rb:615:in `initialize'
	from test.rb:4:in `new'
	from test.rb:4:in `<main>'

I'm running as root and get the same output with both the 2015-03-01 and 2015-07-06 console images.

**Comment by notnyt** [comment]
I'll look into this shortly.  Have you had any other code running before this?  Does this happen right after a reboot?
What is this console image you're referring to?  Please provide a link.  I'll check with the debian build from latest-images page soon.

**Comment by Luis-Castillo** [comment]
https://rcn-ee.com/rootfs/bb.org/release/2015-07-06/console/BBB-eMMC-flasher-debian-7.8-console-armhf-2015-07-06-2gb.img.xz

I don't have a monitor attached but I understand is a "console only" image without software pre installed.  Just installed ruby and the gem and go into it with ssh.

dmesg shows:

[ 1524.957159] bone-capemgr bone_capemgr.9: slot #13: 'Override Board Name,00A0,Override Manuf,GPIO_P9_12_0x17'
[ 1524.957247] bone-capemgr bone_capemgr.9: slot #13: Requesting part number/version based 'GPIO_P9_12_0x17-00A0.dtbo
[ 1524.957263] bone-capemgr bone_capemgr.9: slot #13: Requesting firmware 'GPIO_P9_12_0x17-00A0.dtbo' for board-name 'Override Board Name', version '00A0'
[ 1524.971342] bone-capemgr bone_capemgr.9: failed to load firmware 'GPIO_P9_12_0x17-00A0.dtbo'

**Comment by notnyt** [comment]
Those images do not have the dtc application installed by default, and as such, cannot compile the necessary .dtbo files.

**Comment by notnyt** [comment]
Try again after running: apt-get install device-tree-compiler

**Comment by notnyt** [comment]
run: apt-get install device-tree-compiler

This should fix your issue.

root@beaglebone:~# apt-get install device-tree-compiler
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  device-tree-compiler
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 367 kB of archives.
After this operation, 466 kB of additional disk space will be used.
Get:1 http://repos.rcn-ee.com/debian/ wheezy/main device-tree-compiler armhf 1.4.0+dfsg-1bborg~bpo70+20141203+1 [367 kB]
Fetched 367 kB in 0s (776 kB/s)
Selecting previously unselected package device-tree-compiler.
(Reading database ... 12023 files and directories currently installed.)
Unpacking device-tree-compiler (from .../device-tree-compiler_1.4.0+dfsg-1bborg~bpo70+20141203+1_armhf.deb) ...
Setting up device-tree-compiler (1.4.0+dfsg-1bborg~bpo70+20141203+1) ...

root@beaglebone:~# irb
irb(main):001:0> require 'beaglebone'
=> true
irb(main):002:0> include Beaglebone
=> Object
irb(main):003:0>
irb(main):004:0* pin = GPIOPin.new :P9_12, :OUT
=> #<Beaglebone::GPIOPin:0x27dbd8 @pin=:P9_12>

**Comment by Luis-Castillo** [comment]
It's working now, thanks a lot!
