### ISSUE TITLE
Can this library be used as a non root user?

### ISSUE THREAD

**Issue by NickShaffner** [notnyt/beaglebone#3]
For example, entering the line from the readme:

   led1 = GPIOPin.new(:USR0, :OUT)

results in:

   Errno::EACCES: Permission denied - /sys/class/leds/beaglebone:green:usr0/trigger
from /home/crashtest/.rvm/gems/ruby-1.9.3-p547/bundler/gems/beaglebone-c29dbc2db26e/lib/beaglebone/gpio.rb:99:in `initialize'

'groups' for this user:  (yes, tried adding to the root group with no effect)  

   debian root adm dialout cdrom floppy audio dip video plugdev users netdev i2c admin spi

Any idea if it's possible for a non-root user to access the BBB GPIO?   Everything I've found on the net indicates one should use 'sudo'.

Thanks, and awesome library design!

```
 Nick
```

**Comment by growing** [comment]
Hi, thanks for the library.

I've modified the robot control script (mentioned by Nick above) to fix the permissions so that this lib works as a normal user;

https://github.com/growing/RobotControl/blob/master/contrib/fix_udev_gpio.sh

Cheers,

Dan
