### ISSUE TITLE
run_on_edge/wait_for_edge doesn't wait with parallel UDPSocket

### ISSUE THREAD

**Issue by micheletedeschi** [notnyt/beaglebone#5]
run_on_edge/wait_for_edge doesn't wait for edge if I use in parallel an UDPSocket.
The problem is in "wait_for_edge", after socket.send IO.select call receive an interrupt and wakes up.

**Comment by notnyt** [comment]
Do you have a code example I can test this with?

This shouldn't happen as my select call is only passed a single descriptor.

https://github.com/notnyt/beaglebone/blob/master/lib/beaglebone/gpio.rb#L268
