### ISSUE TITLE
Not working with cape manager

### ISSUE THREAD

**Issue by alxx** [notnyt/beaglebone#7]
If I enable uBoot (`enable_uboot_overlays=1` in /bin/uEnv.txt) then I can't access GPIOPins using the gem.

```
Beaglebone::GPIOPin.new :P8_13, :OUT
Errno::ENOENT: No such file or directory @ rb_sysopen - /sys/devices/platform/bone_capemgr/slots
```

because in this case there's no `slots` file.

However, I can still write to the gems directly, from the shell:

`echo low > /sys/class/gpio23/direction`

**Comment by notnyt** [comment]
The gem needs to load device tree files to configure the pins.  If you load the uboot overlays it cannot do this.

**Comment by alxx** [comment]
But uBoot is the recommended approach now, as per the BBB docs, and the workaround is relatively simple, for example:

`File.open("/sys/class/gpio/gpio23/direction", 'a+') do |f|; f.puts "low"; end`

Will this gem never support uBoot for GPIO?

**Comment by notnyt** [comment]
If I find time I may be able to add support, but it's not likely.  This method does not support changing pullup/pulldown, slew rate, and other features that dynamic loading of device tree files allows.
